In [5]:
import random
import pandas as pd

file=open('pubdata.txt','w+')
status=['Economy','Medium','Luxury']
zone=['North','East','West','South']
cuisine=['SouthIndian','NorthIndian','Vegetarian','Vegan','European','African','Asian']

file.write('zone,status,cuisine,guests\n')
for i in range(1000):
    
    file.write(str(random.choice(zone)+','+random.choice(status)+','+random.choice(cuisine)+','+str(random.randint(1,10))+'\n'))


file.close()

In [6]:
df= pd.read_csv('pubdata.txt')
df

      zone   status      cuisine  guests
0    South   Luxury   Vegetarian       8
1     West   Luxury   Vegetarian       6
2     West  Economy   Vegetarian       7
3    North   Luxury        Vegan       7
4     West   Medium   Vegetarian       2
5    North   Luxury   Vegetarian       5
6     East  Economy     European       7
7    North   Medium  SouthIndian       8
8     West   Luxury   Vegetarian       1
9    North   Medium     European       7
10    West  Economy     European      10
11    East  Economy        Vegan       9
12   North   Luxury  NorthIndian       8
13   South  Economy        Vegan       9
14   South  Economy   Vegetarian       4
15   North   Medium        Vegan      10
16    East  Economy        Asian       2
17    West   Medium        Vegan       4
18    West  Economy     European       5
19   North   Medium  NorthIndian       2
20   South   Medium        Asian       6
21    West   Medium  NorthIndian       8
22    East  Economy     European       8
23   North   Medium        Vegan       2
24    West  Economy     European       5
25    East  Economy        Vegan       3
26   South   Luxury      African       6
27    West   Luxury      African       2
28   North   Medium      African       7
29    West   Medium   Vegetarian       6
..     ...      ...          ...     ...
970  North   Medium   Vegetarian       3
971   West   Medium        Vegan      10
972   East  Economy     European       2
973  South   Luxury        Asian       4
974  North   Luxury        Asian       8
975  South   Luxury        Vegan       8
976   East   Luxury        Asian       6
977  South   Luxury      African       7
978  South  Economy  NorthIndian       6
979  South   Luxury   Vegetarian       5
980  South   Luxury     European       6
981  South   Luxury  NorthIndian       6
982   East   Luxury   Vegetarian       1
983  South   Medium      African       9
984  South   Medium        Vegan       3
985  South  Economy        Asian       6
986  South  Economy  SouthIndian      10
987   West   Luxury        Vegan       7
988   East  Economy      African       3
989   West   Luxury      African       5
990  South  Economy      African       9
991  South  Economy  SouthIndian       9
992  North   Luxury        Vegan       7
993   West  Economy      African       8
994  North   Luxury  SouthIndian       9
995  South   Medium     European       2
996  South   Medium        Vegan       8
997   East   Medium     European       6
998  South  Economy      African       7
999   East   Luxury     European       2

[1000 rows x 4 columns]

In [8]:
x=df[(df['cuisine'] == 'Vegan' )&(df['status'] == 'Luxury' )&(df['guests']==7)&(df['zone']=='North') ]
print(x)
x=x.to_dict(orient='list')

      zone  status cuisine  guests
3    North  Luxury   Vegan       7
220  North  Luxury   Vegan       7
560  North  Luxury   Vegan       7
781  North  Luxury   Vegan       7
992  North  Luxury   Vegan       7

In [9]:
print('A table for '+str(x['guests'][0]) +' is booked in '+ x['zone'][0]+' zone. Cuisine: ' + x['cuisine'][0] + ' .Budget choice: '+ x['status'][0] +'.' )

A table for 7 is booked in North zone. Cuisine: Vegan .Budget choice: Luxury.